parameters:
    is_stage_required: false
    stages_to_allow_existing_tag: []

services:
    _defaults:
        autowire: true
        public: true

    Symplify\MonorepoBuilder\Release\:
        resource: '../src'
        exclude:
            - '../src/Exception/*'
            # register manually in desired order + allows add your own
            - '../src/ReleaseWorker/*'
